[build]
builder = "NIXPACKS"
buildCommand = "npm install && npm run build && node build-api.mjs"

[deploy]
startCommand = "node server.mjs"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
