[build]
builder = "NIXPACKS"
buildCommand = "echo 'no build required'"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["curl"]

[deploy]
startCommand = "curl -s -X POST $APP_URL/api/notifications/check-landlord-due-dates -H 'Authorization: Bearer $CRON_SECRET' -H 'Content-Type: application/json'"
cronSchedule = "0 0 * * *"
restartPolicyType = "NEVER"
