[build]
builder = "NIXPACKS"
buildCommand = "echo 'no build required'"

[build.nixpacksPlan.phases.setup]
nixPkgs = ["nodejs_20"]

[deploy]
startCommand = "node anything/apps/web/scripts/cron-check-due-dates.mjs"
cronSchedule = "0 0 * * *"
restartPolicyType = "NEVER"